
language: node_js
node_js:
    - "4"



before_install:
install:
    - npm install -g gulp-cli
    - npm install -g gitbook-cli

before_script:
    - npm install
    - gitbook install

script:
    - gitbook build

after_success: |
    - 

after_failure:
before_deploy:
deploy:
after_deploy:
after_script:
