
language: node_js
node_js:
    - "4"

before_install:
install:
    - npm install -g gulp-cli
    - npm install -g gitbook-cli

before_script:
    - npm install
    - gitbook install

script:
    - gulp
    - gitbook build

after_success: |
    if [ -n "$GITHUB_API_KEY" ]; then
        cd "$TRAVIS_BUILD_DIR"
        git checkout gh-pages
        cp -fr _book/* .
        git -c user.name='travis' -c user.email='travis' commit -m 'travis-ci build'
        # Make sure to make the output quiet, or else the API token will leak!
        # This works because the API key can replace your password.
        git push -f -q https://btpka3:$GITHUB_API_KEY@github.com/btpka3/btpka3.git gh-pages &2>/dev/null
        cd "$TRAVIS_BUILD_DIR"
    fi

after_failure:
before_deploy:
deploy:
after_deploy:
after_script:
